import{a as L,S as b,i as f}from"./assets/vendor-ee72e1a4.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();async function p(t,e){const r="https://pixabay.com",l="/api/",o=new URLSearchParams({key:"44054875-23597af336816bebd19227040",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e});try{const{data:s}=await L(`${r}${l}?${o}`);return s}catch(s){console.error(s.message)}}function m(t){return t.map(e=>`<li class="element-gallery">
      <a class="gallery-link" href="${e.largeImageURL}">
    <img class="img-gallery" src="${e.webformatURL}" alt="${e.tags}">
    <ul class="list-info">
    <li class="item-info"><h3 class="title-text">Likes</h3>
    <p class="text">${e.likes}</p></li>
    <li class="item-info"><h3 class="title-text">Views</h3>
    <p class="text">${e.views}</p></li>
    <li class="item-info"><h3 class="title-text">Comments</h3>
    <p class="text">${e.comments}</p></li>
    <li class="item-info"><h3 class="title-text">Downloads</h3>
    <p class="text">${e.downloads}</p></li>
   </ul>
  </li>`).join("")}function g(){new b(".gallery a",{captionDelay:250,captionsData:"alt"}).refresh()}function h(){const t=document.querySelector(".loader");t.style.display="block"}function c(){const t=document.querySelector(".loader");t.style.display="none"}const w=document.querySelector(".form"),y=document.querySelector('input[name = "value"]'),d=document.querySelector(".gallery"),n=document.querySelector(".btn-load-more");n.style.display="none";c();let i="";w.addEventListener("submit",async t=>{if(t.preventDefault(),d.innerHTML="",i=y.value.trim(),i!==""){y.value="",h();try{const{hits:e,totalHits:r}=await p(i,a=1);if(console.log(r),console.log(e),!e||e.length===0){f.error({message:"Sorry, there are no images matching your search query. Please try again!"}),n.style.display="none";return}const l=m(e);d.insertAdjacentHTML("beforeend",l),g(),r>15?n.style.display="block":n.style.display="none"}catch(e){console.log(e)}finally{c()}console.log(a)}});let a=1;n.addEventListener("click",async()=>{a+=1,h();try{const{hits:t}=await p(i,a);if(console.log(a),!t||t.length===0){c(),f.error({position:"topRight",message:"We're sorry, there are no more posts to load"}),n.style.display="none";return}d.insertAdjacentHTML("beforeend",m(t)),g();const r=d.lastElementChild.getBoundingClientRect().height;window.scrollBy({left:0,top:r*2,behavior:"smooth"})}catch(t){console.log(t)}finally{c()}});
//# sourceMappingURL=commonHelpers.js.map
