import{a as L,i as f,S as b}from"./assets/vendor-ee72e1a4.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();async function p(t,e=1){const s="https://pixabay.com",n="/api/",o=new URLSearchParams({key:"44054875-23597af336816bebd19227040",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e});try{const{data:r}=await L(`${s}${n}?${o}`);if(r.hits.length===0)f.error({message:"Sorry, there are no images matching your search query. Please try again!"});else return r.hits}catch(r){console.error(r.message)}}function m(t){return t.map(e=>`<li class="element-gallery">
      <a class="gallery-link" href="${e.largeImageURL}">
    <img class="img-gallery" src="${e.webformatURL}" alt="${e.tags}">
    <ul class="list-info">
    <li class="item-info"><h3 class="title-text">Likes</h3>
    <p class="text">${e.likes}</p></li>
    <li class="item-info"><h3 class="title-text">Views</h3>
    <p class="text">${e.views}</p></li>
    <li class="item-info"><h3 class="title-text">Comments</h3>
    <p class="text">${e.comments}</p></li>
    <li class="item-info"><h3 class="title-text">Downloads</h3>
    <p class="text">${e.downloads}</p></li>
   </ul>
  </li>`).join("")}function h(){new b(".gallery a",{captionDelay:250,captionsData:"alt"}).refresh()}function g(){const t=document.querySelector(".loader");t.style.display="block"}function i(){const t=document.querySelector(".loader");t.style.display="none"}const w=document.querySelector(".form"),y=document.querySelector('input[name = "value"]'),c=document.querySelector(".gallery"),l=document.querySelector(".btn-load-more");l.style.display="none";i();let a="",u=1;w.addEventListener("submit",async t=>{if(t.preventDefault(),c.innerHTML="",a=y.value.trim(),a!==""){y.value="",g();try{const e=await p(a,u);if(!e||e.length===0){l.style.display="none";return}const s=m(e);c.insertAdjacentHTML("beforeend",s),h(),e.length>=15?l.style.display="block":l.style.display="none"}catch(e){console.log(e)}finally{i()}}});l.addEventListener("click",async()=>{u+=1,g();try{const t=await p(a,u);if(!t||t.length===0){i(),f.error({position:"topRight",message:"We're sorry, there are no more posts to load"}),l.style.display="none";return}c.insertAdjacentHTML("beforeend",m(t)),h();const s=c.lastElementChild.getBoundingClientRect().height;window.scrollBy({left:0,top:s*2,behavior:"smooth"})}catch(t){console.log(t)}finally{i()}});
//# sourceMappingURL=commonHelpers.js.map
